dbt_project_flights:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      schema: development
      database: development
      username: root
      password: root
      ssl_disabled: True

      